-- AlterTable
ALTER TABLE `NewsArticle` MODIFY `modifiedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Topic` MODIFY `modifiedOn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
